name: Update dependencies

on: 
  schedule:
  # At 20:20 UTC every day.
  - cron: '20 20 * * *'
  
  repository_dispatch:
    types: update-dependencies

  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update dependencies
    uses: CCSWE-nanoframework/actions-nanoframework/.github/workflows/update-dependencies.yml@master
    secrets: inherit
    with:
      solution: 'CCSWE.nanoFramework.Threading.sln'
      branchToPr: 'master'